{
 "title": "Mimir / Git-sync",
 "tags": [ "mimir" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(git_fetch_count_total,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(git_fetch_count_total{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(git_fetch_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(git_fetch_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Git operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Git sync/fetch per minute",
   "type": "timeseries",
   "description": "How many git syncs completed, partitioned by state (success, error, noop) & How many git fetches were run\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(git_sync_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]) * 60) by (status)",
     "legendFormat": "sync: {{status}}"
    },
    {
     "expr": "sum(rate(git_fetch_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]) * 60)",
     "legendFormat": "fetch"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(git_sync_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) by (status) /\r\nsum(rate(git_sync_duration_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "K8s", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Replicas with git-sync sidecar",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{cluster=~\"$cluster\", namespace=~\"$namespace\", deployment=~\"$job\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_ready{cluster=~\"$cluster\", namespace=~\"$namespace\", deployment=~\"$job\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_deployment_spec_replicas{cluster=~\"$cluster\", namespace=~\"$namespace\", deployment=~\"$job\"})",
     "legendFormat": "Desired"
    }
   ]
  },
  {
   "title": "Phases of pods with git-sync sidecar",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container restarts per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"git-sync\", pod=~\"$pod\"}[$__rate_interval]) * 60) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(kube_pod_init_container_status_restarts_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"git-sync-init\", pod=~\"$pod\"}[$__rate_interval]) * 60) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Terminated containers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"git-sync\", pod=~\"$pod\"}) by (container)",
     "legendFormat": "Terminated - {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"git-sync\", pod=~\"$pod\"}) by (container, reason)",
     "legendFormat": "Reason - {{container}} - {{reason}}"
    },
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"git-sync\", pod=~\"$pod\"}) by (container, reason)",
     "legendFormat": "Last reason  - {{container}} - {{reason}}"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"git-sync-init\", pod=~\"$pod\"}) by (container)",
     "legendFormat": "Terminated - {{container}}"
    },
    {
     "expr": "sum(kube_pod_init_container_status_terminated_reason{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"git-sync-init\", pod=~\"$pod\"}) by (container, reason)",
     "legendFormat": "Reason - {{container}} - {{reason}}"
    },
    {
     "expr": "sum(kube_pod_init_container_status_last_terminated_reason{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"git-sync-init\", pod=~\"$pod\"}) by (container, reason)",
     "legendFormat": "Last reason  - {{container}} - {{reason}}"
    }
   ]
  },
  {
   "title": "Image version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"git-sync\", pod=~\"$pod\"}) by (image, container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_init_container_info{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"git-sync-init\", pod=~\"$pod\"}) by (image, container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(time() - kube_pod_start_time{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "{k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", k8s_deployment_name=~\"$job\", k8s_container_name=\"git-sync\"} | json"
      }
     ]
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"git-sync\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"git-sync\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=\"git-sync\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\",container=\"git-sync\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"git-sync\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"git-sync\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\",container=\"git-sync\",resource=\"cpu\", pod=~\"$pod\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=\"git-sync\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=\"git-sync\", pod=~\"$pod\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\",container=\"git-sync\",resource=\"memory\", pod=~\"$pod\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=\"git-sync\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network TODO fix missing container label",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true
  }
 ]
}